# Generated by Django 4.0.2 on 2022-02-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='titulo',
            new_name='title',
        ),
    ]
